Repository assemblee-virtuelle/semapps, pull requests merged in 2019-12, with the labels that each got.

#54 config by url instead ENV
  sources/SolidMiddleware/boilerplate/runner/index.js
  sources/SolidMiddleware/boilerplate/runner/package.json
Labels: ready

#57 Use application/sparql-query instead of x-www-form-urlencoded
  sources/SolidMiddleware/packages/triplestore/index.js
Labels: ready

#60 Frontend initial setup
  .gitignore
  docker-compose.yaml
  sources/SolidMiddleware/boilerplate/runner/index.js
  sources/SolidMiddleware/packages/activitypub/routes.js
  sources/frontend/Dockerfile
  sources/frontend/README.md
  sources/frontend/entrypoint.sh
  sources/frontend/package.json
  sources/frontend/public/index.html
  sources/frontend/src/App.css
  sources/frontend/src/App.js
  sources/frontend/src/index.css
  sources/frontend/src/index.js
  sources/frontend/yarn.lock
Labels: ready

#70 Improve automatic containers results
  sources/SolidMiddleware/packages/LDP/index.js
Labels: ready

#69 Merge standard and automatic containers
  sources/SolidMiddleware/packages/LDP/index.js
  sources/frontend/src/App.js
Labels: ready

#71 Rename directories and add conventions
  Makefile
  README.md
  docker-compose-prod.yaml
  docker-compose.yaml
  docs/conventions.md
  sources/SolidMiddleware/boilerplate/runner/package-lock.json
  src/frontend/Dockerfile
  src/frontend/README.md
  src/frontend/entrypoint.sh
  src/frontend/package.json
  src/frontend/public/index.html
  src/frontend/src/App.css
  src/frontend/src/App.js
  src/frontend/src/NoteService.js
  src/frontend/src/index.css
  src/frontend/src/index.js
  src/frontend/yarn.lock
  src/middleware/Dockerfile
  src/middleware/README.md
  src/middleware/boilerplates/runner/index.js
  src/middleware/boilerplates/runner/package.json
  src/middleware/lerna.json
  src/middleware/package-lock.json
  src/middleware/package.json
  src/middleware/packages/activitypub/constants.js
  src/middleware/packages/activitypub/index.js
  src/middleware/packages/activitypub/package-lock.json
  src/middleware/packages/activitypub/package.json
  src/middleware/packages/activitypub/routes.js
  src/middleware/packages/activitypub/services/outbox.js
  src/middleware/packages/fuseki-admin/index.js
  src/middleware/packages/fuseki-admin/package-lock.json
  src/middleware/packages/fuseki-admin/package.json
  src/middleware/packages/ldp/index.js
  src/middleware/packages/ldp/package-lock.json
  src/middleware/packages/ldp/package.json
  src/middleware/packages/triplestore/index.js
  src/middleware/packages/triplestore/package-lock.json
  src/middleware/packages/triplestore/package.json
Labels: ready

#74 Fix and improve triplestore for JSON queries
  src/middleware/boilerplates/runner/package-lock.json
  src/middleware/packages/ldp/index.js
  src/middleware/packages/triplestore/constants.js
  src/middleware/packages/triplestore/index.js
Labels: ready

#75 Handle outbox properly
  src/middleware/boilerplates/runner/index.js
  src/middleware/packages/activitypub/index.js
  src/middleware/packages/activitypub/services/collection.js
  src/middleware/packages/activitypub/services/outbox.js
Labels: ActivityPub, ready

#81 New Follow service
  src/middleware/boilerplates/runner/index.js
  src/middleware/packages/activitypub/constants.js
  src/middleware/packages/activitypub/index.js
  src/middleware/packages/activitypub/routes.js
  src/middleware/packages/activitypub/services/collection.js
  src/middleware/packages/activitypub/services/follow.js
  src/middleware/packages/activitypub/services/outbox.js
Labels: ActivityPub, ready

#82 New Inbox service
  src/middleware/boilerplates/runner/index.js
  src/middleware/packages/activitypub/constants.js
  src/middleware/packages/activitypub/index.js
  src/middleware/packages/activitypub/routes.js
  src/middleware/packages/activitypub/services/inbox.js
  src/middleware/packages/activitypub/services/outbox.js
Labels: ActivityPub, ready

#89 Handle followers list as recipient
  src/middleware/packages/activitypub/constants.js
  src/middleware/packages/activitypub/services/collection.js
  src/middleware/packages/activitypub/services/inbox.js
  src/middleware/packages/activitypub/services/outbox.js
  src/middleware/packages/ldp/index.js
Labels: activitypub

#93 Automatic launch of prettier on every PR
  .github/workflows/prettier_format.yml
  Makefile
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/App.css
  src/frontend/src/index.css
  src/frontend/yarn.lock
Labels: dev, ready
