Repository assemblee-virtuelle/semapps, pull requests merged in 2020-01, with the labels that each got.

#94 Basic LDP API #84
  .gitignore
  src/frontend/yarn.lock
  src/middleware/boilerplates/runner/index.js
  src/middleware/packages/activitypub/routes.js
  src/middleware/packages/ldp/README.md
  src/middleware/packages/ldp/index.js
  src/middleware/packages/ldp/package-lock.json
  src/middleware/packages/ldp/package.json
  src/middleware/packages/triplestore/constants.js
  src/middleware/packages/triplestore/index.js
Labels: ldp

#91 Add initial integration tests
  .github/workflows/integration_tests.yml
  .github/workflows/prettier_format.yml
  Makefile
  src/middleware/boilerplates/runner/createServices.js
  src/middleware/boilerplates/runner/index.js
  src/middleware/boilerplates/runner/package-lock.json
  src/middleware/boilerplates/runner/package.json
  src/middleware/boilerplates/runner/test/activitypub.test.js
  src/middleware/boilerplates/runner/test/middleware/EventsWatcher.js
  src/middleware/packages/activitypub/services/follow.js
  src/middleware/packages/activitypub/services/inbox.js
  src/middleware/packages/triplestore/index.js
Labels: dev

#96 Front user management
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/public/index.html
  src/frontend/src/App.css
  src/frontend/src/App.js
  src/frontend/src/CreateUser.js
  src/frontend/src/NoteService.js
  src/frontend/src/SendMessage.js
  src/frontend/src/UserPreview.js
  src/frontend/src/UserProfile.js
  src/frontend/src/Users.js
  src/frontend/src/api/initStore.js
  src/frontend/src/api/reducer.js
  src/frontend/src/api/useQuery.js
  src/frontend/src/constants.js
  src/frontend/src/index.css
  src/frontend/src/index.js
  src/frontend/src/utils.js
  src/frontend/yarn.lock
  src/middleware/boilerplates/runner/createServices.js
  src/middleware/packages/ldp/index.js
Labels: frontend, ready

#99 #84 LDP PATCH
  src/middleware/packages/ldp/README.md
  src/middleware/packages/ldp/index.js
  src/middleware/packages/triplestore/index.js
  src/middleware/packages/triplestore/package-lock.json
  src/middleware/packages/triplestore/package.json
Labels: ldp, ready

#102 Fix LDP patch
  src/middleware/packages/triplestore/index.js
Labels: ready

#103 Front - User edit
  src/frontend/src/App.js
  src/frontend/src/UserPreview.js
  src/frontend/src/UserProfile.js
  src/frontend/src/Users.js
  src/frontend/src/api/actions.js
  src/frontend/src/api/reducer.js
  src/frontend/src/api/useQuery.js
  src/frontend/src/constants.js
  src/frontend/src/forms/CreateUserForm.js
  src/frontend/src/forms/EditUserForm.js
  src/frontend/src/forms/SendMessageForm.js
Labels: frontend, ready

#105 Config .env vars for frontend
  src/frontend/.env
  src/frontend/.gitignore
  src/frontend/src/UserProfile.js
  src/frontend/src/Users.js
  src/frontend/src/config.js
  src/frontend/src/constants.js
  src/frontend/src/forms/CreateUserForm.js
  src/frontend/src/forms/EditUserForm.js
  src/frontend/src/forms/SendMessageForm.js
Labels: ready

#107 Middleware env config
  docker-compose-prod.yaml
  docker-compose.yaml
  src/middleware/boilerplates/runner/.env
  src/middleware/boilerplates/runner/.env.test
  src/middleware/boilerplates/runner/.gitignore
  src/middleware/boilerplates/runner/config.js
  src/middleware/boilerplates/runner/createServices.js
  src/middleware/boilerplates/runner/index.js
  src/middleware/boilerplates/runner/ontologies.json
  src/middleware/boilerplates/runner/package-lock.json
  src/middleware/boilerplates/runner/package.json
  src/middleware/boilerplates/runner/test/activitypub.test.js
  src/middleware/packages/ldp/index.js
Labels: ready

#108 100 auth oidc
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/App.js
  src/frontend/src/UserPreview.js
  src/frontend/src/UserProfile.js
  src/frontend/src/Users.js
  src/frontend/src/forms/CreateUserForm.js
  src/frontend/src/forms/EditUserForm.js
  src/frontend/yarn.lock
  src/middleware/boilerplates/runner/auth/middlware-oidc.js
  src/middleware/boilerplates/runner/auth/passport-oidc.js
  src/middleware/boilerplates/runner/createServices.js
  src/middleware/boilerplates/runner/index.js
  src/middleware/boilerplates/runner/package-lock.json
  src/middleware/boilerplates/runner/package.json
  src/middleware/packages/ldp/index.js
Labels: ready

#110 @id instead id in LDP POST to support @vocab in @context
  src/middleware/packages/ldp/index.js
Labels: ldp, ready

#109 OIDC + CAS login
  src/frontend/.env
  src/frontend/src/App.js
  src/frontend/src/NavBar.js
  src/frontend/src/Page.js
  src/frontend/src/UserPreview.js
  src/frontend/src/UserProfile.js
  src/frontend/src/Users.js
  src/frontend/src/api/useQuery.js
  src/frontend/src/auth/useAuth.js
  src/frontend/src/config.js
  src/frontend/src/forms/CreateUserForm.js
  src/frontend/src/forms/EditUserForm.js
  src/frontend/src/forms/SendMessageForm.js
  src/middleware/Dockerfile
  src/middleware/boilerplates/runner/.env
  src/middleware/boilerplates/runner/.gitignore
  src/middleware/boilerplates/runner/auth/middlware-oidc.js
  src/middleware/boilerplates/runner/auth/passport-oidc.js
  src/middleware/boilerplates/runner/config.js
  src/middleware/boilerplates/runner/configureExpress.js
  src/middleware/boilerplates/runner/createServices.js
  src/middleware/boilerplates/runner/index.js
  src/middleware/boilerplates/runner/jwt/.gitkeep
  src/middleware/boilerplates/runner/package-lock.json
  src/middleware/boilerplates/runner/package.json
  src/middleware/packages/activitypub/routes.js
  src/middleware/packages/connector/CasConnector.js
  src/middleware/packages/connector/Connector.js
  src/middleware/packages/connector/OidcConnector.js
  src/middleware/packages/connector/index.js
  src/middleware/packages/connector/package-lock.json
  src/middleware/packages/connector/package.json
  src/middleware/packages/ldp/index.js
  src/middleware/packages/ldp/routes.js
  src/middleware/packages/ldp/service.js
Labels: ready

#118 DELETE and INSERT AFTER instead both same time
  src/middleware/boilerplates/runner/ontologies.json
  src/middleware/packages/triplestore/index.js
Labels: ldp, ready
