Repository assemblee-virtuelle/semapps, pull requests merged in 2020-05, with the labels that each got.

#245 LDP container clear action
  src/middleware/packages/ldp/adapter.js
  src/middleware/packages/ldp/services/container/actions/clear.js
  src/middleware/packages/ldp/services/container/index.js
  src/middleware/packages/triplestore/package-lock.json
  src/middleware/tests/ldp/container.test.js
Labels: ldp, ready

#166 Push notifications service
  src/middleware/packages/importer/package.json
  src/middleware/packages/push/LICENSE
  src/middleware/packages/push/index.js
  src/middleware/packages/push/package-lock.json
  src/middleware/packages/push/package.json
  src/middleware/packages/push/service.js
  src/middleware/packages/push/services/device.js
  src/middleware/packages/push/services/notification.js
Labels: ready, reconnexion

#253 Extract @semapps/react-admin package
  src/frontend/dms/config-overrides.js
  src/frontend/dms/package-lock.json
  src/frontend/dms/package.json
  src/frontend/dms/src/App.js
  src/frontend/dms/src/resources/concepts.js
  src/frontend/dms/src/resources/organizations.js
  src/frontend/dms/src/resources/projects.js
  src/frontend/dms/src/semapps/index.js
  src/frontend/lerna.json
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/packages/react-admin/activitypub/ActivitiesGrid.js
  src/frontend/packages/react-admin/activitypub/ActivitiesList.js
  src/frontend/packages/react-admin/activitypub/ActivityDescription.js
  src/frontend/packages/react-admin/activitypub/ActorsGrid.js
  src/frontend/packages/react-admin/activitypub/CollectionList.js
  src/frontend/packages/react-admin/authProvider.js
  src/frontend/packages/react-admin/copyValues.js
  src/frontend/packages/react-admin/dataProvider.js
  src/frontend/packages/react-admin/httpClient.js
  src/frontend/packages/react-admin/index.js
  src/frontend/packages/react-admin/inputs.js
  src/frontend/packages/react-admin/package-lock.json
  src/frontend/packages/react-admin/package.json
Labels: ready

#260 Build react-admin package for NPM publish
  src/frontend/dms/.env
  src/frontend/dms/config-overrides.js
  src/frontend/dms/package-lock.json
  src/frontend/dms/package.json
  src/frontend/lerna.json
  src/frontend/package.json
  src/frontend/packages/react-admin/.babelrc
  src/frontend/packages/react-admin/README.md
  src/frontend/packages/react-admin/dist/index.cjs.js
  src/frontend/packages/react-admin/dist/index.es.js
  src/frontend/packages/react-admin/package-lock.json
  src/frontend/packages/react-admin/package.json
  src/frontend/packages/react-admin/rollup.config.js
  src/frontend/packages/react-admin/src/activitypub/ActivitiesGrid.js
  src/frontend/packages/react-admin/src/activitypub/ActivitiesList.js
  src/frontend/packages/react-admin/src/activitypub/ActivityDescription.js
  src/frontend/packages/react-admin/src/activitypub/ActorsGrid.js
  src/frontend/packages/react-admin/src/activitypub/CollectionList.js
  src/frontend/packages/react-admin/src/authProvider.js
  src/frontend/packages/react-admin/src/copyValues.js
  src/frontend/packages/react-admin/src/dataProvider.js
  src/frontend/packages/react-admin/src/httpClient.js
  src/frontend/packages/react-admin/src/index.js
  src/frontend/packages/react-admin/src/inputs.js
Labels: ready

#261 Generate MongoDB-like UUIDs
  src/middleware/packages/ldp/package-lock.json
  src/middleware/packages/ldp/package.json
  src/middleware/packages/ldp/utils.js
Labels: ready

#264 Fix LDP container and AP collection returned types
  src/middleware/packages/activitypub/services/collection.js
  src/middleware/packages/ldp/services/container/actions/get.js
  src/middleware/tests/ldp/container.test.js
Labels: ready

#157 ActivityPub Bot
  src/middleware/packages/activitypub/index.js
  src/middleware/packages/activitypub/mixins/bot.js
  src/middleware/packages/activitypub/services/actor.js
  src/middleware/packages/activitypub/services/collection.js
  src/middleware/packages/ldp/services/resource/actions/delete.js
Labels: ready

#266 upgrade make & docker environement
  .env
  Makefile
  docker-compose.yaml
  src/frontend/Dockerfile.dev
  src/frontend/packages/react-admin/package-lock.json
Labels: devops, devx, frontend, ready

#192 Add fuseki.semapps.org subdomain
  deploy/nginx/app.conf
  init-letsencrypt.sh
Labels: ready

#254 Mise à jour de l'équipe SemApps
  website/docs/governance/team.md
Labels: external doc

#272 add many file support for sparql query
  src/middleware/packages/middlewares/package-lock.json
  src/middleware/packages/middlewares/package.json
  src/middleware/packages/mime-types/constants.js
  src/middleware/packages/sparql-endpoint/getRoutes.js
  src/middleware/packages/triplestore/index.js
  src/middleware/packages/webid/getRoutes.js
Labels: backend, ready

#271 246 refactoring sparql endpoint + web
  Makefile
  src/middleware/boilerplates/runner/services/api.service.js
  src/middleware/boilerplates/runner/services/ldp.service.js
  src/middleware/boilerplates/runner/services/sparql-endpoint.service.js
  src/middleware/packages/ldp/package.json
  src/middleware/packages/ldp/routes/getContainerRoutes.js
  src/middleware/packages/middlewares/LICENSE
  src/middleware/packages/middlewares/index.js
  src/middleware/packages/middlewares/package-lock.json
  src/middleware/packages/middlewares/package.json
  src/middleware/packages/mime-types/constants.js
  src/middleware/packages/sparql-endpoint/getRoutes.js
  src/middleware/packages/sparql-endpoint/index.js
  src/middleware/packages/sparql-endpoint/package-lock.json
  src/middleware/packages/sparql-endpoint/package.json
  src/middleware/packages/sparql-endpoint/routes.js
  src/middleware/packages/sparql-endpoint/service.js
  src/middleware/packages/triplestore/index.js
  src/middleware/packages/webid/getRoutes.js
  src/middleware/packages/webid/index.js
  src/middleware/packages/webid/package.json
  src/middleware/packages/webid/routes.js
  src/middleware/packages/webid/service.js
  src/middleware/tests/package.json
Labels: backend, ready

#193 Technical documentation
  website/docs/guides/ldp-server.md
  website/docs/others/ACL.md
  website/docs/others/PropertiesContainer.md
  website/docs/others/basicLDP.md
  website/docs/others/conventions.md
  website/docs/packages/activitypub.md
  website/docs/packages/connector.md
  website/docs/packages/importer.md
  website/docs/packages/ldp.md
  website/docs/packages/triplestore.md
  website/docs/packages/webhooks.md
  website/docs/packages/webid.md
  website/docs/participate/style-guide.md
  website/docusaurus.config.js
  website/package-lock.json
  website/package.json
  website/sidebars.js
Labels: ready, technical doc

#227 Docs / How to document
  website/docs/participate/documentation.md
  website/docusaurus.config.js
  website/sidebars.js
Labels: external doc, not ready

#268 Refactoring des 3 phrases
  website/src/pages/index.js
Labels: external doc

#280 localData description update
  website/docs/guides/ldp-server.md
Labels: external doc

#274 DMS template
  src/frontend/cra-template-dms/README.md
  src/frontend/cra-template-dms/package.json
  src/frontend/cra-template-dms/template.json
  src/frontend/cra-template-dms/template/.env
  src/frontend/cra-template-dms/template/README.md
  src/frontend/cra-template-dms/template/gitignore
  src/frontend/cra-template-dms/template/public/favicon.ico
  src/frontend/cra-template-dms/template/public/index.html
  src/frontend/cra-template-dms/template/public/logo192.png
  src/frontend/cra-template-dms/template/public/logo512.png
  src/frontend/cra-template-dms/template/public/manifest.json
  src/frontend/cra-template-dms/template/public/robots.txt
  src/frontend/cra-template-dms/template/src/App.js
  src/frontend/cra-template-dms/template/src/auth/LogoutButton.js
  src/frontend/cra-template-dms/template/src/components/SearchFilter.js
  src/frontend/cra-template-dms/template/src/config/ontologies.json
  src/frontend/cra-template-dms/template/src/config/resources.js
  src/frontend/cra-template-dms/template/src/index.css
  src/frontend/cra-template-dms/template/src/index.js
  src/frontend/cra-template-dms/template/src/resources/persons.js
  src/frontend/dms/package-lock.json
  src/frontend/dms/package.json
  src/frontend/lerna.json
  src/frontend/package.json
  src/frontend/packages/react-admin/package-lock.json
  src/frontend/packages/react-admin/package.json
  src/frontend/playground/package-lock.json
  src/frontend/playground/package.json
Labels: frontend, ready
