Repository assemblee-virtuelle/semapps, pull requests merged in 2020-02, with the labels that each got.

#121 CAS logout
  src/frontend/src/pages/MyProfilePage.js
  src/middleware/boilerplates/runner/.env
  src/middleware/boilerplates/runner/configureExpress.js
  src/middleware/packages/connector/CasConnector.js
  src/middleware/packages/connector/Connector.js
  src/middleware/packages/connector/OidcConnector.js
Labels: ready

#111 101 slug
  src/middleware/boilerplates/runner/package-lock.json
  src/middleware/packages/connector/package-lock.json
  src/middleware/packages/ldp/index.js
  src/middleware/packages/ldp/service.js
Labels: ldp, ready

#122 Generate ActivityPub actors on WebID creation
  src/frontend/src/pages/MyProfilePage.js
  src/middleware/boilerplates/runner/createServices.js
  src/middleware/boilerplates/runner/test/activitypub.test.js
  src/middleware/boilerplates/runner/test/middleware/EventsWatcher.js
  src/middleware/packages/activitypub/createServices.js
  src/middleware/packages/activitypub/index.js
  src/middleware/packages/activitypub/routes.js
  src/middleware/packages/activitypub/services/actor.js
  src/middleware/packages/activitypub/services/collection.js
  src/middleware/packages/activitypub/services/follow.js
  src/middleware/packages/activitypub/services/inbox.js
  src/middleware/packages/activitypub/services/outbox.js
  src/middleware/packages/fuseki-admin/index.js
  src/middleware/packages/ldp/service.js
  src/middleware/packages/triplestore/index.js
  src/middleware/packages/webid/service.js
Labels: ready

#127 Frontend ActivityPub integration
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/App.js
  src/frontend/src/Inbox.js
  src/frontend/src/NavBar.js
  src/frontend/src/Page.js
  src/frontend/src/ResourceField.js
  src/frontend/src/ResourcePreview.js
  src/frontend/src/ResourceValue.js
  src/frontend/src/api/reducer.js
  src/frontend/src/api/useQuery.js
  src/frontend/src/app/reducer.js
  src/frontend/src/auth/useAuth.js
  src/frontend/src/config.js
  src/frontend/src/forms/SendMessageForm.js
  src/frontend/src/pages/MessagesPage.js
  src/frontend/src/pages/ResourceCreatePage.js
  src/frontend/src/pages/ResourceDeletePage.js
  src/frontend/src/pages/ResourceEditPage.js
  src/frontend/src/pages/ResourceViewPage.js
  src/frontend/src/pages/ResourcesListPage.js
  src/frontend/src/resourcesTypes.js
  src/frontend/src/utils.js
  src/frontend/yarn.lock
  src/middleware/packages/activitypub/services/actor.js
  src/middleware/packages/webid/routes.js
  src/middleware/packages/webid/service.js
Labels: ready

#135 Allow user to logout globally or locally
  src/frontend/public/index.html
  src/frontend/src/pages/MyProfilePage.js
  src/middleware/packages/connector/Connector.js
  src/middleware/packages/connector/OidcConnector.js
Labels: authentification, ready

#133 124 deconnexion oidc
  src/frontend/package-lock.json
  src/frontend/public/index.html
  src/frontend/src/pages/MyProfilePage.js
  src/middleware/packages/connector/Connector.js
  src/middleware/packages/connector/OidcConnector.js
Labels: authentification, ready

#158 Adapt getWebID for CAS connector
  src/middleware/packages/connector/Connector.js
Labels: ready

#162 Upgrade to Moleculer 0.14
  src/middleware/boilerplates/runner/package-lock.json
  src/middleware/boilerplates/runner/package.json
  src/middleware/boilerplates/runner/test/middleware/EventsWatcher.js
  src/middleware/packages/activitypub/package-lock.json
  src/middleware/packages/activitypub/package.json
  src/middleware/packages/activitypub/services/actor.js
  src/middleware/packages/activitypub/services/follow.js
  src/middleware/packages/activitypub/services/inbox.js
  src/middleware/packages/connector/package-lock.json
  src/middleware/packages/connector/package.json
  src/middleware/packages/ldp/package-lock.json
  src/middleware/packages/ldp/package.json
  src/middleware/packages/mime-types/package-lock.json
  src/middleware/packages/mime-types/package.json
Labels: ready

#164 Launch all ActivityPub sub-services with a single service
  src/middleware/boilerplates/runner/createServices.js
  src/middleware/packages/activitypub/index.js
  src/middleware/packages/activitypub/service.js
Labels: ready
