Repository assemblee-virtuelle/semapps, pull requests merged in 2020-03, with the labels that each got.

#167 Incoming webhooks service
  Makefile
  docker-compose.yaml
  src/middleware/boilerplates/runner/configureExpress.js
  src/middleware/boilerplates/runner/createServices.js
  src/middleware/boilerplates/runner/index.js
  src/middleware/boilerplates/runner/package-lock.json
  src/middleware/boilerplates/runner/package.json
  src/middleware/packages/ldp/adapter.js
  src/middleware/packages/webhooks/README.md
  src/middleware/packages/webhooks/index.js
  src/middleware/packages/webhooks/package-lock.json
  src/middleware/packages/webhooks/package.json
  src/middleware/packages/webhooks/routes.js
  src/middleware/packages/webhooks/service.js
Labels: ready, reconnexion

#173 Move playground to own directory
  Makefile
  docker-compose-prod.yaml
  docker-compose.yaml
  src/frontend/playground/.env
  src/frontend/playground/.gitignore
  src/frontend/playground/Dockerfile
  src/frontend/playground/README.md
  src/frontend/playground/entrypoint.sh
  src/frontend/playground/package-lock.json
  src/frontend/playground/package.json
  src/frontend/playground/public/index.html
  src/frontend/playground/src/App.js
  src/frontend/playground/src/App.scss
  src/frontend/playground/src/Inbox.js
  src/frontend/playground/src/NavBar.js
  src/frontend/playground/src/Page.js
  src/frontend/playground/src/ResourceField.js
  src/frontend/playground/src/ResourcePreview.js
  src/frontend/playground/src/ResourceValue.js
  src/frontend/playground/src/api/actions.js
  src/frontend/playground/src/api/reducer.js
  src/frontend/playground/src/api/useQuery.js
  src/frontend/playground/src/app/actions.js
  src/frontend/playground/src/app/reducer.js
  src/frontend/playground/src/auth/UserProvider.js
  src/frontend/playground/src/auth/useAuth.js
  src/frontend/playground/src/config.js
  src/frontend/playground/src/index.js
  src/frontend/playground/src/pages/MessagesPage.js
  src/frontend/playground/src/pages/MyProfilePage.js
  src/frontend/playground/src/pages/ResourceCreatePage.js
  src/frontend/playground/src/pages/ResourceDeletePage.js
  src/frontend/playground/src/pages/ResourceEditPage.js
  src/frontend/playground/src/pages/ResourceViewPage.js
  src/frontend/playground/src/pages/ResourcesListPage.js
  src/frontend/playground/src/redux/initStore.js
  src/frontend/playground/src/resourcesTypes.js
  src/frontend/playground/src/utils.js
  src/frontend/playground/yarn.lock
Labels: ready

#174 Clean, consistent LDP get results
  src/middleware/packages/ldp/actions/get.js
  src/middleware/packages/ldp/services/container.js
  src/middleware/packages/triplestore/index.js
Labels: ldp, question

#149 nginx and certbot for playground
  .gitignore
  README.md
  deploy/fuseki/Makefile
  deploy/fuseki/docker-compose.yaml
  deploy/nginx/app.conf
  docker-compose-prod.yaml
  init-letsencrypt.sh
  src/middleware/Dockerfile
  src/middleware/lerna.json
Labels: ready

#178 LDP get : slug and containerUri parameters
  src/middleware/packages/ldp/actions/post.js
  src/middleware/packages/ldp/service.js
Labels: ldp, ready

#177 Allow to run different boilerplates and frontend
  .env
  docker-compose-prod.yaml
  docker-compose.yaml
  src/middleware/Dockerfile
  src/middleware/boilerplates/runner/entrypoint.sh
Labels: dev, ready

#175 React Admin frontend
  src/frontend/dms/.gitignore
  src/frontend/dms/README.md
  src/frontend/dms/package.json
  src/frontend/dms/public/favicon.ico
  src/frontend/dms/public/index.html
  src/frontend/dms/public/logo192.png
  src/frontend/dms/public/logo512.png
  src/frontend/dms/public/manifest.json
  src/frontend/dms/public/robots.txt
  src/frontend/dms/src/App.css
  src/frontend/dms/src/App.js
  src/frontend/dms/src/auth/LogoutButton.js
  src/frontend/dms/src/authProvider.js
  src/frontend/dms/src/httpClient.js
  src/frontend/dms/src/index.css
  src/frontend/dms/src/index.js
  src/frontend/dms/src/ldpDataProvider.js
  src/frontend/dms/src/resources/organizations.js
  src/frontend/dms/src/resources/persons.js
  src/frontend/dms/src/resources/projects.js
  src/frontend/dms/src/utils/jsonLdInputs.js
  src/frontend/dms/yarn.lock
  src/middleware/boilerplates/runner/.env
Labels: dms, ready

#184 Run frontend in production mode
  docker-compose-prod.yaml
  docker-compose.yaml
  src/frontend/.dockerignore
  src/frontend/Dockerfile.dev
  src/frontend/Dockerfile.prod
  src/frontend/dms/README.md
  src/frontend/dms/yarn.lock
  src/frontend/playground/Dockerfile
  src/frontend/playground/README.md
  src/frontend/playground/entrypoint.sh
  src/frontend/playground/src/NavBar.js
  src/frontend/playground/src/ResourcePreview.js
  src/frontend/playground/src/pages/ResourceEditPage.js
  src/frontend/playground/src/pages/ResourceViewPage.js
  src/frontend/playground/src/pages/ResourcesListPage.js
  src/frontend/playground/src/resourcesTypes.js
  src/frontend/playground/src/utils.js
Labels: ready

#190 webId called ldp with bad prameters
  src/middleware/packages/webid/service.js
  src/middleware/tests/webId/config.js
  src/middleware/tests/webId/ontologies.json
  src/middleware/tests/webId/webId.test.js
Labels: authentification, ldp, ready

#187 126 ldp test integration
  src/frontend/playground/yarn.lock
  src/middleware/boilerplates/runner/package-lock.json
  src/middleware/packages/webhooks/package-lock.json
  src/middleware/tests/ldp/config.js
  src/middleware/tests/ldp/ldp.test.js
  src/middleware/tests/ldp/ldp_api.test.js
  src/middleware/tests/ldp/ontologies.json
  src/middleware/tests/package-lock.json
  src/middleware/tests/package.json
Labels: ldp, ready

#179 Importer service
  src/middleware/packages/importer/index.js
  src/middleware/packages/importer/package.json
  src/middleware/packages/importer/service.js
Labels: ready
