Repository assemblee-virtuelle/semapps, pull requests merged in 2021-03, with the labels that each got.

#619 MapList: add option to connect markers
  src/frontend/packages/geo-components/README.md
  src/frontend/packages/geo-components/dist/index.cjs.js
  src/frontend/packages/geo-components/dist/index.es.js
  src/frontend/packages/geo-components/src/MapList.js
Labels: ready

#621 Fix all links in Archipelago
  src/frontend/boilerplates/archipelago/package-lock.json
  src/frontend/boilerplates/archipelago/package.json
  src/frontend/boilerplates/archipelago/public/unknown-user.png
  src/frontend/boilerplates/archipelago/src/resources/Agent/Activity/Activity.js
  src/frontend/boilerplates/archipelago/src/resources/Agent/Activity/ActivityShow.js
  src/frontend/boilerplates/archipelago/src/resources/Agent/Activity/Event/EventShow.js
  src/frontend/boilerplates/archipelago/src/resources/Agent/Activity/Event/index.js
  src/frontend/boilerplates/archipelago/src/resources/Agent/Activity/Project/ProjectShow.js
  src/frontend/boilerplates/archipelago/src/resources/Agent/Activity/Project/index.js
  src/frontend/boilerplates/archipelago/src/resources/Agent/Actor/Actor.js
  src/frontend/boilerplates/archipelago/src/resources/Agent/Actor/Organization/OrganizationShow.js
  src/frontend/boilerplates/archipelago/src/resources/Agent/Actor/Organization/index.js
  src/frontend/boilerplates/archipelago/src/resources/Agent/Actor/Person/PersonList.js
  src/frontend/boilerplates/archipelago/src/resources/Agent/Actor/Person/PersonShow.js
  src/frontend/boilerplates/archipelago/src/resources/Agent/Actor/Person/index.js
  src/frontend/boilerplates/archipelago/src/resources/Agent/Agent.js
  src/frontend/boilerplates/archipelago/src/resources/Concept/Theme/ThemeList.js
  src/frontend/boilerplates/archipelago/src/resources/Concept/Theme/ThemeShow.js
  src/frontend/boilerplates/archipelago/src/resources/Concept/Theme/index.js
  src/frontend/boilerplates/archipelago/src/resources/Object/Document/DocumentList.js
  src/frontend/boilerplates/archipelago/src/resources/Object/Document/DocumentShow.js
  src/frontend/boilerplates/archipelago/src/resources/Object/Document/index.js
  src/frontend/boilerplates/archipelago/src/resources/Resource/Skill/SkillList.js
  src/frontend/boilerplates/archipelago/src/resources/Resource/Skill/SkillShow.js
  src/frontend/packages/archipelago-layout/dist/index.cjs.js
  src/frontend/packages/archipelago-layout/dist/index.es.js
  src/frontend/packages/archipelago-layout/package.json
  src/frontend/packages/archipelago-layout/src/index.js
  src/frontend/packages/archipelago-layout/src/show/AvatarField.js
  src/frontend/packages/archipelago-layout/src/show/RedirectByType.js
  src/frontend/packages/archipelago-layout/src/show/UserIcon.js
  src/frontend/packages/auth-provider/package.json
  src/frontend/packages/date-components/package.json
  src/frontend/packages/geo-components/package.json
  src/frontend/packages/react-admin/package.json
  src/frontend/packages/semantic-data-provider/package.json
Labels: ready

#618 small improvement for react admin
  src/frontend/boilerplates/archipelago/package.json
  src/frontend/boilerplates/archipelago/public/index.html
  src/frontend/boilerplates/archipelago/src/App.js
  src/frontend/packages/auth-provider/dist/index.cjs.js
  src/frontend/packages/auth-provider/dist/index.es.js
  src/frontend/packages/auth-provider/src/authProvider.js
  src/frontend/packages/auth-provider/src/components/LoginPage.js
Labels: Archipel, frontend

#640 Allow ReferenceInput and ReferenceField to handle dereferenced fields
  src/frontend/boilerplates/archipelago/src/resources/Agent/Activity/Event/EventShow.js
  src/frontend/boilerplates/archipelago/src/resources/Agent/Activity/Project/ProjectShow.js
  src/frontend/boilerplates/archipelago/src/resources/Agent/Actor/Organization/OrganizationShow.js
  src/frontend/boilerplates/archipelago/src/resources/Agent/Actor/Person/PersonShow.js
  src/frontend/boilerplates/archipelago/src/resources/Concept/Theme/ThemeShow.js
  src/frontend/boilerplates/archipelago/src/resources/Object/Document/DocumentShow.js
  src/frontend/boilerplates/archipelago/src/resources/Resource/Skill/SkillShow.js
  src/frontend/packages/semantic-data-provider/dist/index.cjs.js
  src/frontend/packages/semantic-data-provider/dist/index.es.js
  src/frontend/packages/semantic-data-provider/src/fields/ReferenceArrayField.js
  src/frontend/packages/semantic-data-provider/src/fields/ReferenceField.js
  src/frontend/packages/semantic-data-provider/src/fields/UriArrayField.js
  src/frontend/packages/semantic-data-provider/src/index.js
  src/frontend/packages/semantic-data-provider/src/inputs/ReferenceArrayInput.js
  src/frontend/packages/semantic-data-provider/src/inputs/ReferenceInput.js
  src/middleware/boilerplates/pair-ldp-server/containers.js
Labels: ready

#637 Add types and status to Archipelago
  src/frontend/boilerplates/archipelago/src/resources/Concept/Status/StatusCreate.js
  src/frontend/boilerplates/archipelago/src/resources/Concept/Status/StatusEdit.js
  src/frontend/boilerplates/archipelago/src/resources/Concept/Status/StatusList.js
  src/frontend/boilerplates/archipelago/src/resources/Concept/Status/StatusTitle.js
  src/frontend/boilerplates/archipelago/src/resources/Concept/Status/index.js
  src/frontend/boilerplates/archipelago/src/resources/Concept/Type/TypeCreate.js
  src/frontend/boilerplates/archipelago/src/resources/Concept/Type/TypeEdit.js
  src/frontend/boilerplates/archipelago/src/resources/Concept/Type/TypeList.js
  src/frontend/boilerplates/archipelago/src/resources/Concept/Type/TypeTitle.js
  src/frontend/boilerplates/archipelago/src/resources/Concept/Type/index.js
  src/frontend/boilerplates/archipelago/src/resources/Object/Document/DocumentEdit.js
  src/frontend/boilerplates/archipelago/src/resources/Object/Document/DocumentShow.js
  src/frontend/boilerplates/archipelago/src/resources/Object/Document/index.js
  src/frontend/boilerplates/archipelago/src/resources/Object/Folder/index.js
  src/frontend/boilerplates/archipelago/src/resources/index.js
Labels: ready

#582 relation réifiées grace à la configuration disassembly du container et au ArrayInput+SimpleFormIterator de react-admin
  Makefile
  src/frontend/boilerplates/archipelago/src/resources/Agent/Actor/Organization/OrganizationEdit.js
  src/frontend/boilerplates/archipelago/src/resources/Agent/Actor/Organization/index.js
  src/frontend/boilerplates/archipelago/src/resources/Concept/MembershipRole/RoleCreate.js
  src/frontend/boilerplates/archipelago/src/resources/Concept/MembershipRole/RoleEdit.js
  src/frontend/boilerplates/archipelago/src/resources/Concept/MembershipRole/RoleList.js
  src/frontend/boilerplates/archipelago/src/resources/Concept/MembershipRole/index.js
  src/frontend/boilerplates/archipelago/src/resources/index.js
  src/frontend/packages/semantic-data-provider/dist/index.cjs.js
  src/frontend/packages/semantic-data-provider/dist/index.es.js
  src/frontend/packages/semantic-data-provider/src/dataProvider.js
  src/frontend/packages/semantic-data-provider/src/index.js
  src/frontend/packages/semantic-data-provider/src/inputs/ReificationArrayInput.js
  src/middleware/boilerplates/pair-ldp-server/containers.js
  src/middleware/packages/connector/index.js
  src/middleware/packages/ldp/services/container/actions/attach.js
  src/middleware/packages/ldp/services/resource/actions/delete.js
  src/middleware/packages/ldp/services/resource/actions/get.js
  src/middleware/packages/ldp/services/resource/actions/patch.js
  src/middleware/packages/ldp/services/resource/actions/post.js
  src/middleware/packages/ldp/services/resource/actions/put.js
  src/middleware/packages/ldp/services/resource/methods.js
  src/middleware/packages/ldp/utils.js
  src/middleware/packages/triplestore/index.js
  src/middleware/tests/activitypub/object.test.js
  src/middleware/tests/ldp/resourceDisassembly.test.js
  website/docs/others/basicLDP.md
  website/docs/others/reifiedRelation.md
Labels: ready

#634 AccordionList component
  src/frontend/packages/archipelago-layout/dist/index.cjs.js
  src/frontend/packages/archipelago-layout/dist/index.es.js
  src/frontend/packages/archipelago-layout/src/index.js
  src/frontend/packages/archipelago-layout/src/list/AccordionList.js
  src/frontend/packages/archipelago-layout/src/show/LargeLabel.js
  src/frontend/packages/archipelago-layout/src/show/MainList.js
  src/frontend/packages/auth-provider/dist/index.cjs.js
  src/frontend/packages/auth-provider/dist/index.es.js
  src/frontend/packages/react-admin/dist/index.cjs.js
  src/frontend/packages/react-admin/dist/index.es.js
Labels: ready

#645 Add boundToMarkers option to MapList
  src/frontend/package.json
  src/frontend/packages/geo-components/README.md
  src/frontend/packages/geo-components/dist/index.cjs.js
  src/frontend/packages/geo-components/dist/index.es.js
  src/frontend/packages/geo-components/src/MapList.js
Labels: ready

#648 FilteredArrayField & ReifiedArrayField pour show les relation réifiées
  src/frontend/boilerplates/archipelago/src/resources/Agent/Activity/Event/EventFilterSidebar.js
  src/frontend/boilerplates/archipelago/src/resources/Agent/Activity/Event/EventList.js
  src/frontend/boilerplates/archipelago/src/resources/Agent/Activity/Project/ProjectEdit.js
  src/frontend/boilerplates/archipelago/src/resources/Agent/Activity/Project/ProjectFilterSidebar.js
  src/frontend/boilerplates/archipelago/src/resources/Agent/Activity/Project/ProjectList.js
  src/frontend/boilerplates/archipelago/src/resources/Agent/Actor/Organization/OrganizationEdit.js
  src/frontend/boilerplates/archipelago/src/resources/Agent/Actor/Organization/OrganizationFilterSidebar.js
  src/frontend/boilerplates/archipelago/src/resources/Agent/Actor/Organization/OrganizationList.js
  src/frontend/boilerplates/archipelago/src/resources/Agent/Actor/Organization/OrganizationShow.js
  src/frontend/boilerplates/archipelago/src/resources/Agent/Actor/Person/PersonFilterSidebar.js
  src/frontend/boilerplates/archipelago/src/resources/Concept/MembershipRole/RoleEdit.js
  src/frontend/boilerplates/archipelago/src/resources/Concept/MembershipRole/RoleList.js
  src/frontend/boilerplates/archipelago/src/resources/Resource/Resource.js
  src/frontend/boilerplates/archipelago/src/resources/Resource/Skill/SkillShow.js
  src/frontend/packages/archipelago-layout/dist/index.cjs.js
  src/frontend/packages/archipelago-layout/dist/index.es.js
  src/frontend/packages/archipelago-layout/src/fields/AvatarField.js
  src/frontend/packages/archipelago-layout/src/index.js
  src/frontend/packages/archipelago-layout/src/list/ReferenceFilter.js
  src/frontend/packages/archipelago-layout/src/show/RightLabel.js
  src/frontend/packages/archipelago-layout/src/show/UserIcon.js
  src/frontend/packages/semantic-data-provider/dist/index.cjs.js
  src/frontend/packages/semantic-data-provider/dist/index.es.js
  src/frontend/packages/semantic-data-provider/src/dataProvider.js
  src/frontend/packages/semantic-data-provider/src/fields/FilteredArrayField.js
  src/frontend/packages/semantic-data-provider/src/fields/GroupedArrayField.js
  src/frontend/packages/semantic-data-provider/src/fields/ReferenceArrayField.js
  src/frontend/packages/semantic-data-provider/src/index.js
Labels: frontend, ready
