Repository assemblee-virtuelle/semapps, pull requests merged in 2021-01, with the labels that each got.

#492 Flexible containers with ActivityPub
  src/middleware/boilerplates/pair-ldp-server/.gitignore
  src/middleware/boilerplates/pair-ldp-server/containers.js
  src/middleware/boilerplates/pair-ldp-server/package.json
  src/middleware/boilerplates/pair-ldp-server/public/context.json
  src/middleware/boilerplates/pair-ldp-server/services/activitypub.service.js
  src/middleware/boilerplates/pair-ldp-server/services/api.service.js
  src/middleware/boilerplates/pair-ldp-server/services/backup.service.js
  src/middleware/boilerplates/pair-ldp-server/services/ldp.service.js
  src/middleware/boilerplates/pair-ldp-server/services/signature.service.js
  src/middleware/boilerplates/pair-ldp-server/services/webfinger.service.js
  src/middleware/packages/activitypub/containers.js
  src/middleware/packages/activitypub/index.js
  src/middleware/packages/activitypub/service.js
  src/middleware/packages/activitypub/services/actor.js
  src/middleware/packages/activitypub/services/collection.js
  src/middleware/packages/activitypub/services/dispatch.js
  src/middleware/packages/activitypub/services/follow.js
  src/middleware/packages/activitypub/services/inbox.js
  src/middleware/packages/activitypub/services/object.js
  src/middleware/packages/activitypub/services/outbox.js
  src/middleware/packages/backup/index.js
  src/middleware/packages/fuseki-admin/index.js
  src/middleware/packages/ldp/service.js
  src/middleware/packages/ldp/services/container/actions/get.js
  src/middleware/packages/ldp/services/container/index.js
  src/middleware/packages/ldp/services/resource/actions/get.js
  src/middleware/packages/ldp/services/resource/actions/patch.js
  src/middleware/packages/ldp/services/resource/actions/post.js
  src/middleware/packages/ldp/services/resource/actions/put.js
  src/middleware/packages/ldp/services/resource/index.js
  src/middleware/packages/ldp/services/resource/methods.js
  src/middleware/packages/middlewares/index.js
  src/middleware/packages/signature/service.js
  src/middleware/packages/triplestore/index.js
  src/middleware/packages/webid/service.js
  src/middleware/tests/activitypub/follow.test.js
  src/middleware/tests/activitypub/initialize.js
  src/middleware/tests/activitypub/object.test.js
  website/docs/packages/backup.md
  website/docs/packages/ldp.md
Labels: ready

#503 Dereference container option
  src/middleware/boilerplates/pair-ldp-server/containers.js
  src/middleware/boilerplates/pair-ldp-server/ontologies.json
  src/middleware/packages/activitypub/containers.js
  src/middleware/packages/activitypub/services/actor.js
  src/middleware/packages/ldp/adapter.js
  src/middleware/packages/ldp/services/container/actions/get.js
  src/middleware/packages/ldp/services/resource/actions/get.js
  src/middleware/packages/ldp/utils.js
  src/middleware/tests/ldp/container.test.js
  src/middleware/tests/ontologies.json
Labels: ready

#504 Fix and improve ldp.container.get action
  src/middleware/packages/ldp/services/container/actions/clear.js
  src/middleware/packages/ldp/services/container/actions/get.js
  src/middleware/packages/ldp/utils.js
  src/middleware/tests/ldp/container.test.js
Labels: ready

#510 Mets à jour les rôles sur le site web
  website/docs/governance/organisation-and-roles.md
Labels: ready

#514 AutocompleteArrayInput autocompletion restore
  src/frontend/packages/semantic-data-provider/dist/index.cjs.js
  src/frontend/packages/semantic-data-provider/dist/index.es.js
  src/frontend/packages/semantic-data-provider/src/dataProvider.js
Labels: frontend, ready

#518 Fix files uploads
  src/middleware/packages/middlewares/index.js
Labels: ready

#520 archipelago bugfix
  src/frontend/boilerplates/archipelago/package-lock.json
  src/frontend/boilerplates/archipelago/src/inputs.js
  src/frontend/boilerplates/archipelago/src/resources/Document/DocumentShow.js
  src/frontend/boilerplates/archipelago/src/resources/Skill/SkillList.js
  src/frontend/boilerplates/archipelago/src/resources/Skill/SkillShow.js
  src/frontend/boilerplates/archipelago/src/resources/Skill/index.js
  src/frontend/boilerplates/archipelago/src/resources/Theme/ThemeShow.js
  src/frontend/boilerplates/archipelago/src/resources/User/UserShow.js
Labels: Archipel, frontend, ready

#530 Improve data provider filtering
  src/frontend/boilerplates/archipelago/package-lock.json
  src/frontend/boilerplates/archipelago/package.json
  src/frontend/package.json
  src/frontend/packages/semantic-data-provider/dist/index.cjs.js
  src/frontend/packages/semantic-data-provider/dist/index.es.js
  src/frontend/packages/semantic-data-provider/src/buildSparqlQuery.js
  src/frontend/packages/semantic-data-provider/src/dataProvider.js
  src/middleware/package-lock.json
  src/middleware/package.json
  src/middleware/packages/activitypub/services/actor.js
  src/middleware/packages/activitypub/services/follow.js
  src/middleware/packages/ldp/services/resource/actions/patch.js
  src/middleware/packages/webhooks/service.js
Labels: breaking changes

#534 Move container options to ldp.container service
  src/middleware/packages/ldp/service.js
  src/middleware/packages/ldp/services/container/actions/get.js
  src/middleware/packages/ldp/services/container/actions/getOptions.js
  src/middleware/packages/ldp/services/container/defaultOptions.js
  src/middleware/packages/ldp/services/container/index.js
  src/middleware/packages/ldp/services/resource/actions/get.js
  src/middleware/packages/ldp/services/resource/actions/patch.js
Labels: ready

#538 Improve ActivityPub handling
  src/middleware/packages/activitypub/mixins/bot.js
  src/middleware/packages/activitypub/services/actor.js
  src/middleware/packages/activitypub/services/dispatch.js
  src/middleware/packages/activitypub/services/follow.js
  src/middleware/packages/activitypub/services/outbox.js
  src/middleware/packages/activitypub/utils.js
Labels: breaking changes, ready
